# THE GOAL OF THIS SCRIPT IS TO, GIVEN A INPUT 'checks_RunXXXXX.h5' WITH THE DATA OBTAINED FROM FILTER 1 AND 2, MAINLY, IF THERE ARE ANY ANOMALOUS SUBRUNS ('CHECKS') OR NOT, AND THEIR RELATIVE INFORMATION,
# DO SOME STATISTICAL ANALYSIS OF THE RESULTS, THEN, GENERATE AN OUTPUT 'classified_runs.h5' FILE THAT CONTAINS HOW MANY INTERESING, NORMAL OR UNVALID RUNS THERE HAVE BEEN AND BY WHICH FILTER THEY WERE CATALOGUED AS SUCH.
import glob 
import argparse  

import re
import tables

import numpy as np
import statsmodels.api as sm


# INSERTING THE PATH OF THE CHECKS ---------------------------------------------------------------------------------------------------------

parser = argparse.ArgumentParser(description="This is my code") # parser is the object that will read the arguments, description will appear when python prueba.py --help

parser.add_argument(
    "-d", "--datacheck",
    required=True,
    help="Input datacheck file"
)


parser.add_argument(
    "-c", "--checks",
    required=True,
    help="checks_RunXXXX.h5 file generated by toy2.py"
)

def main():
    args = parser.parse_args()

    datacheck_list = sorted(glob.glob(args.datacheck))
    checks_list = sorted(glob.glob(args.checks))

    checks_dict = {
        (re.search(r"Run(\d+)", f).group(1)): f
        for f in checks_list
        if re.search(r"Run(\d+)", f)}

    paired_files = []

    for datacheck_file in datacheck_list:
        m = re.search(r"Run(\d+)", datacheck_file)
        if m:
            run = m.group(1)
            if run in checks_dict:
                paired_files.append((datacheck_file, checks_dict[run]))

    n_total_runs = 0  # count how many observations we have used

    filters = ["1", "2", "2a", "2b", "2c"]
    disfunctional = {f: [] for f in filters}

    # Run Ids
    normal_runs = []
    invalid_runs = []
    anomalous_runs = []

    # Observation times
    normal_time = 0
    invalid_time = 0
    anomalous_time = 0

    for datacheck_file, checks_file in paired_files:
        n_total_runs += 1  # count how many observations we have used

        a = None
        b = None

        try:
            a = tables.open_file(datacheck_file)
            b = tables.open_file(checks_file)

            run = re.search(r"Run(\d+)", b.filename).group(1)  # saves correctly the run id's starting on 0, int() takes the numerical value

            run_time = float(np.sum(a.root.dl1datacheck.cosmics.col("elapsed_time")[:-1]))   # elapsed time in seconds

            checks = b.root.general.cosmics.col("subrun_index")
            # CLASSIFICATION OF TYPE OF RUN AND STORING OF ELAPSED TIME OF THE RUN ---------------------
            validity = {}

            for f in filters:
                fit_table = getattr(b.root.perfilter, f"filter{f}_fit")
                valid = fit_table[0]["valid"]
                validity[f] = valid  # store the validity for every filter

                if not valid:
                    disfunctional[f].append(run)

            if len(checks) == 0:
                if not any(validity.values()):  # if none of the filters are valid, it's an invalid run
                    invalid_runs.append(run)
                    invalid_time += run_time
                else:
                    normal_runs.append(run)  # if some filter is valid, it is just a normal run
                    normal_time += run_time
            else:
                anomalous_runs.append(run)
                anomalous_time += run_time

        except Exception as e:
            print(f"Error {datacheck_file} / {checks_file}: {e}")

        finally:
            if a is not None:
                a.close()
            if b is not None:
                b.close()

    total_time = normal_time + invalid_time + anomalous_time
            
    # CREATION OF AN h5 FILE TO STORE THE ANALYSIS OF THE RESULTS----------------------------------------------------------------------------------
    statistics_h5 = tables.open_file(r"runs_statistics.h5", mode="w") 
    
    # In these files, we want to store:
    #total_runs : total amount of runs within the 6 years
    #interesting_runs : interesting runs within the total
    #invalid_runs : invalid runs within the total
    #normal_runs : normal runs within the total
    
    # and then, for each of those runs, store the elapsed time of the observation

    # COUNTERS OF KINDS OF RUNS (saved as attributes)-------------------------------
    statistics_h5.root._v_attrs.total_runs = n_total_runs
    
    statistics_h5.root._v_attrs.anomalous_runs = anomalous_runs
    statistics_h5.root._v_attrs.invalid_runs = invalid_runs
    statistics_h5.root._v_attrs.normal_runs = normal_runs

    statistics_h5.root._v_attrs.anomalous_time = anomalous_time
    statistics_h5.root._v_attrs.invalid_time = invalid_time
    statistics_h5.root._v_attrs.normal_time = normal_time
    statistics_h5.root._v_attrs.total_time = total_time
    
    statistics_h5.close()

if __name__ == "__main__":
    main()