import glob # to search files using paths
import argparse  # to give an argument when executing the script

import re
import tables

from ctapipe.visualization import CameraDisplay
from ctapipe.coordinates import EngineeringCameraFrame
from ctapipe_io_lst import LSTEventSource

import numpy as np
import statsmodels.api as sm

from sklearn.decomposition import PCA
from shapely.geometry import LineString, Point
from scipy.stats import chi2


# INSERTING THE PATH OF THE CHECKS AND DATACHECK FILE TO WORK WITH---------------------------------------------------------------------------------------------------------
parser = argparse.ArgumentParser()

parser.add_argument(
    "-d", "--datacheck",
    required=True,
    help="Input datacheck file"
)

parser.add_argument(
    "-c", "--checks",
    required=True,
    help="checks_RunXXXX.h5 file generated by toy2.py"
)

parser.add_argument(      # batch = set of files 
    "--batch-size",
    type=int,
    default=None,
    help="Number of files per batch"
)

parser.add_argument(     # starting point if the set of files
    "--batch",
    type=int,
    default=0,
    help="Batch number (starting from 0)"
)

# ROBUST FIT FUNCTION 
def robust_fitt(x, y, z_thresh=3.5):
    X = x.astype(float).reshape(-1, 1)
    Xc = sm.add_constant(X)
    fit = np.zeros_like(y, dtype=float)
    slope = np.zeros(y.shape[1])
    u_slope = np.zeros(y.shape[1])
    intercept = np.zeros(y.shape[1])
    u_intercept = np.zeros(y.shape[1])
    good_points = []
    valid = []  # True/False per column
    good_masks = [] #to get the positions of the good points

    for p in range(y.shape[1]):
        yp = y[:, p]
        model = sm.OLS(yp, Xc).fit()
        residual = np.abs(yp - model.predict(Xc))
        mad = np.median(np.abs(residual - np.median(residual)))
        mad = max(mad, 1e-12)  # avoid division by zero
        modified_z = 0.6745 * residual / mad
        good = modified_z <= z_thresh
        good_masks.append(good)
        
        if good.sum() >= 0.6*len(x):  # if we take only 2 points, the line of the fit will cross them exactly, giving sigma=0 (both residuals=0)
            good_points.append((x[good], yp[good]))
            
            model = sm.OLS(yp[good], Xc[good]).fit()
            fit[:, p] = model.predict(Xc)
            intercept[p] = model.params[0]
            slope[p] = model.params[1]
            u_intercept[p] = model.bse[0]
            u_slope[p] = model.bse[1]
            
            valid.append(True)
            
        else:
            good_points.append((None, None))
            fit[:, p] = np.nan
            intercept[p] = np.nan
            slope[p] = np.nan
            u_intercept[p] = np.nan
            u_slope[p] = np.nan
            valid.append(False)
        

    return {"fit": fit, "slope": slope, "u_slope": u_slope,
            "intercept": intercept, "u_intercept": u_intercept,
            "good_points": good_points, "good_mask": good_masks, "valid": valid}

"""
fit          :  (len(x), y.shape[1])
slope        :  (y.shape[1],)
u_slope      :  (y.shape[1],)
intercept    :  (y.shape[1],)
u_intercept  :  (y.shape[1],)
good_points  : list of (x_good, y_good) 
good_mask    : list 
valid        : list length y.shape[1]
"""

# WEIGHTED PCA FUNCTION--------------------------------------
def wpca(m, w):
  """
  m : (N, 2)
  w :  (N,)
  
  centroid : (2,)  [x_c, y_c]
  direction_vector : (2,) [u_x, u_y] (unitario)
  """
  w = w / np.sum(w)

  centroid = np.average(m, weights=w, axis=0)

  m_centered = m - centroid # centering data
  cov_matrix = (m_centered.T * w) @ m_centered # covariance matrix

  eigenvalues, eigenvectors = np.linalg.eigh(cov_matrix)
    
  main_axis_index = np.argmax(eigenvalues)
  minor_axis_index = np.argmin(eigenvalues)
    
  direction_vector = eigenvectors[:, main_axis_index]
  minor_axis = eigenvectors[:, minor_axis_index]  


  return centroid, direction_vector, minor_axis

# CAMERA GEOMETRY---------------------- 
sa = LSTEventSource.create_subarray(tel_id=1)
focal_length = sa.tel[1].optics.equivalent_focal_length
camera_geom = sa.tel[1].camera.geometry


def main():
    args = parser.parse_args()

    datacheck_list = sorted(glob.glob(args.datacheck))
    checks_list = sorted(glob.glob(args.checks))
      
    checks_dict = {int(re.search(r"Run(\d+)", f).group(1)): f for f in checks_list}
        
    paired_files = []
    
    for datacheck_file in datacheck_list:
        run = int(re.search(r"Run(\d+)", datacheck_file).group(1))
    
        if run in checks_dict:
            paired_files.append((datacheck_file, checks_dict[run]))

    if args.batch_size is not None:
        start = args.batch * args.batch_size
        end = start + args.batch_size
        paired_files = paired_files[start:end]
       

    disfunctional_3 = []

    
    for datacheck_file, checks_file in paired_files:

        a = tables.open_file(datacheck_file)   # datacheck
        b = tables.open_file(checks_file)      # checks_Run

        run = int(re.search(r"Run(\d+)", datacheck_file).group(1)) # integer number

        # Firstly, check if this run has checks (this includes normal and invalid runs but both are treated equally)               
        checks =  b.root.general.cosmics.col('subrun_index') # look at the checks previously selected by toy2.py and see if they satisfy the condition for Filter 3
        if len(checks) == 0:
            #print(f"Run {run} does not have subruns to check, skip")
            a.close()
            b.close()
            continue

# FILTERS TO DETECT ANOMALIES----------------------------------------------------------------------------------------------------------------------------------
        # First: use the whole original datacheck to see the tendency of the rate of CoG per pixel along subruns
        
        # USEFUL VARIABLES
        subruns = a.root.dl1datacheck.cosmics.col('subrun_index')[:-1] #0,1,...,57 number of subruns in this run
        time = a.root.dl1datacheck.cosmics.col('elapsed_time')[:-1] 
        subrun_to_row = {subrun: row for row, subrun in enumerate(subruns)}

        # FILTER 3: DETECTION OF POTENTIAL SATELLITES/METEORITES BY IDENTIFYING LINEAR TRACES--------------------------------------------------------------------------------------------------
        # we expect the cog within pixel rate to increase with respect to its tendency in the subrun where we have the anomaly in the pixels by which it crosses
        cog_pixel = a.root.dl1datacheck.cosmics.col('cog_within_pixel')[:-1]  # shape: (n_subruns, n_pixels)
        
        cog_rate = cog_pixel / time[:, None]
        cog_sigma = np.sqrt(np.maximum(cog_pixel, 1.0)) / time[:, None] # Poisson-like uncertainty associated to each value
        
        
        # 3.1. FLUCTUATIONS OF COG WITHIN PIXEL 
        # ROBUST FIT TO SELECT PIXELS IN WHICH THE ANOMALY HAS FALLEN 
        cog_robfit = robust_fitt(subruns, cog_rate)  # we are contructing a linear robust fit for each pixel along all the subruns in the run

        if not any(cog_robfit["valid"]):
            disfunctional_3.append(run) 
            a.close()
            b.close()
            continue

        else:
            cog_fit = cog_robfit["fit"]
        
            # Selection criteria
            sigma_cutoff_3 = 3
            cog_z_score = (cog_rate - cog_fit) / cog_sigma
            mask_3 = (cog_z_score) > sigma_cutoff_3 # when taking np.abs(z_score), much more anomalous pixels appear

            
            # SELECTION OF THE PIXELS
            # Select subrun interesting to check according to this filter
            # we'll look at the checks previously selected by toy2.py and see if they satisfy the condition for Filter 3
            
            checks_cog = [] # subruns marked as anomalous by the cog condition

            for c in checks:
                if c not in subrun_to_row:
                    continue
            
                anomalous_row = subrun_to_row[c]
            
                if np.any(mask_3[anomalous_row]):
                    checks_cog.append(c)
  
            if len(checks_cog)==0:
                print(f"No subrun of Run {run} has survived the cutoff, skip")
                a.close()
                b.close()
                continue

# CREATION OF AN h5 FILE TO STORE THOSE SUBRUNS WHO, HAVING BEEN MARKED AS ANOMALOUS BY F1, F2, ARE ALSO ANOMALOUS FOR F3----------------------------------------------------------------------
            chis_h5 = tables.open_file(r"chis_Run{run}.h5".format(run=run), mode="w") 
        
        # In these files, we want to store:
        # checks_3 : subruns to check given by FILTER 3: DETECTION OF STRAIGHT PATHS WITHIN THE INTERESTING SUBRUNS
     
        # and then, for each of those interesting subruns, store the following information:
        # - dof : degrees of freedom of the theoretical chi2 i.e. number of selected pixels - 2(parameters)
        # - centroid and direction vector of the CoG distribuition
        # - CHI2 
        # - p-value


            class Results(tables.IsDescription):
                check_index = tables.Int32Col()
                dof = tables.Int32Col()
                centroid = tables.Float64Col()
                direction_vector = tables.Float64Col()
                chi2 = tables.Float64Col()
                p_value = tables.Float64Col()

            t = chis_h5.create_table("/", "checks", Results, "Interesting subruns and related data according to Filter 3")           
            row = t.row
            
            for check in checks_cog:
# 3.2: PCA FIT OF THE SELECTED PIXELS
# we expect bodies such as satellites (our main interest) or meteorites to cross the camera FoV in a straight trajectory
# to check this, having identified the 'affected' pixels, we aim to do a linear fit (PCA) and determine whether the selected pixels do form a straight line via a Chi^2 test 

# to do the linear fit with the selected pixels, we'll use the PCA method so that our fit does not depend on the frame and we can
# include the cases of completely vertical or horizontal lines

                # Linear fit to check that indeed the path is linear, (Engineering frame: x=-y y=-x)
                anomalous_row = subrun_to_row[check]
                x_pixels = camera_geom.transform_to(EngineeringCameraFrame()).pix_x[mask_3[anomalous_row]].value  # .value to remove the units in the array, 
                y_pixels = camera_geom.transform_to(EngineeringCameraFrame()).pix_y[mask_3[anomalous_row]].value

                if len(x_pixels) < 8:    #impose the selection of at least 8 pixels
                    continue
                
                m_pixels = np.column_stack((x_pixels, y_pixels)) #matrix of the shape columns: pixel, rows: x_pixel, y_pixel

                # Weights for the x and y (are the same for each pixel), the weight will be the normalized cog rate
                cog_rate_anomalous = cog_rate[anomalous_row][mask_3[anomalous_row]]  
                
                # Fit + Elements of the linear fit to draw
                centroid, direction_vector, minor_axis = wpca(m_pixels, cog_rate_anomalous)

                # X^2 TEST TO DETERMINE IF THE PIXELS REALLY FOLLOW A STRAIGHT LINE

                if np.norm(direction_vector) >= 3*np.norm(minor_axis):     
                    # Coordinates of the pixels relative to the centroid
                    delta = m_pixels - centroid
                    
                    #Distances (orthogonal) from the center of the pixels to the line of the fit
                    distances = np.abs(delta[:, 0] * direction_vector[1] - delta[:, 1] * direction_vector[0])
                    
                    # Uncertainty of the points used in the fit
                    sigma_pixel = 0.01 # 1cm
                    
                    # Chi-square
                    # Chi2 Calculated
                    chi2_data = np.sum( cog_rate_anomalous * (distances / sigma_pixel)**2 ) / np.sum(cog_rate_anomalous)
                    dof = len(m_pixels) - 2 #  Number of degrees of freedom of the associated theoretical chi2

            row["check_index"] = check
            row["chi2"] = chi2_data
            row["dof"] = dof

            row.append()
    
    t.flush()
        
    a.close()
    b.close()
    chis_h5.close()

print("Filter 3 could not be applied to Runs: ", disfunctional_3)

if __name__ == '__main__':
    main()


